[package]
name = "rust_olc_pge"
version = "0.1.0"
authors = ["Jonny Kenyon <granitrocky@gmail.com>"]
edition = "2018"


[profile.dev]
opt-level = 0

[profile.test]
opt-level = 2
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_arch = "windows")'.dependencies]
pretty-hex = "0.2.0"
lazy_static = "*"
bmp = "0.5.0"
rand = "*"

[dependencies]
image = "0.23"
png = "*"
bmp = "0.5.0"
cgmath = "0.17"
env_logger = "0.7"
log = "0.4"
wgpu = "0.8"
futures = "0.3"
num-traits = "0.2.14"
pretty-hex ="0.2.0"
lazy_static = "*"
rand = "*"
winit = {  path = "../winit" }
inline-spirv = "0.1.2"
bytemuck = { version = "1.4", features = [ "derive" ] }


[target.'cfg(target_arch="wasm32")'.dependencies]
wasm-bindgen = "0.2.69"
wasm-bindgen-futures = "*"
winit = { path = "../winit", features = ["web-sys"] }
console_log = "0.1.2"
instant = "0.1.9"
console_error_panic_hook = "*"
web-sys = { version = "0.3.50", optional = true, features = ["console","Document","Navigator","Node","NodeList","Gpu","GpuAdapter","GpuAdapterFeatures","GpuAdapterLimits","GpuAddressMode","GpuBindGroup","GpuBindGroupDescriptor","GpuBindGroupEntry","GpuBindGroupLayout","GpuBindGroupLayoutDescriptor","GpuBindGroupLayoutEntry","GpuBlendComponent","GpuBlendFactor","GpuBlendOperation","GpuBlendState","GpuBuffer","GpuBufferBinding","GpuBufferBindingLayout","GpuBufferBindingType","GpuBufferDescriptor","GpuBufferUsage","GpuCanvasContext","GpuColorDict","GpuColorTargetState","GpuColorWrite","GpuCommandBuffer","GpuCommandBufferDescriptor","GpuCommandEncoder","GpuCommandEncoderDescriptor","GpuCompareFunction","GpuCompilationInfo","GpuCompilationMessage","GpuCompilationMessageType","GpuComputePassDescriptor","GpuComputePassEncoder","GpuComputePipeline","GpuComputePipelineDescriptor","GpuCullMode","GpuDepthStencilState","GpuDevice","GpuDeviceDescriptor","GpuDeviceLostInfo","GpuDeviceLostReason","GpuErrorFilter","GpuExtent3dDict","GpuFeatureName","GpuFilterMode","GpuFragmentState","GpuFrontFace","GpuImageCopyBuffer","GpuImageCopyImageBitmap","GpuImageCopyTexture","GpuImageDataLayout","GpuIndexFormat","GpuInputStepMode","GpuLoadOp","GpuMapMode","GpuMultisampleState","GpuObjectDescriptorBase","GpuOrigin2dDict","GpuOrigin3dDict","GpuOutOfMemoryError","GpuPipelineDescriptorBase","GpuPipelineLayout","GpuPipelineLayoutDescriptor","GpuPipelineStatisticName","GpuPowerPreference","GpuPrimitiveState","GpuPrimitiveTopology","GpuProgrammableStage","GpuQuerySet","GpuQuerySetDescriptor","GpuQueryType","GpuQueue","GpuRenderBundle","GpuRenderBundleDescriptor","GpuRenderBundleEncoder","GpuRenderBundleEncoderDescriptor","GpuRenderPassColorAttachment","GpuRenderPassDepthStencilAttachment","GpuRenderPassDescriptor","GpuRenderPassEncoder","GpuRenderPipeline","GpuRenderPipelineDescriptor","GpuRequestAdapterOptions","GpuSampler","GpuSamplerBindingLayout","GpuSamplerBindingType","GpuSamplerDescriptor","GpuShaderModule","GpuShaderModuleDescriptor","GpuShaderStage","GpuStencilFaceState","GpuStencilOperation","GpuStorageTextureAccess","GpuStorageTextureBindingLayout","GpuStoreOp","GpuSwapChain","GpuSwapChainDescriptor","GpuTexture","GpuTextureAspect","GpuTextureBindingLayout","GpuTextureDescriptor","GpuTextureDimension","GpuTextureFormat","GpuTextureSampleType","GpuTextureUsage","GpuTextureView","GpuTextureViewDescriptor","GpuTextureViewDimension","GpuUncapturedErrorEvent","GpuUncapturedErrorEventInit","GpuValidationError","GpuVertexAttribute","GpuVertexBufferLayout","GpuVertexFormat","GpuVertexState","HtmlCanvasElement","Window", "Element"] }
js-sys = "*"

[target.'cfg(target_arch="wasm32")'.dev-dependencies]
console_error_panic_hook = "0.1.6"
console_log = "0.1.2"

[build]
target = "wasm32-unknown-unknown"
